import type { Metadata } from "next";
import Layout from "@/components/Layout";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Overreacted",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Layout>{children}</Layout>;
}
